import { useState, useEffect } from "react";
import { Building2, Plus, Search, Eye, Edit, Trash2, Phone, Mail, MapPin, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Tables, TablesInsert } from "@/integrations/supabase/types";

type Client = Tables<"clients">;
type ClientInsert = TablesInsert<"clients">;

const emptyClient: Omit<ClientInsert, "code"> = {
  raison_sociale: "",
  titre: null,
  adresse: null,
  adresse_facturation: null,
  telephone: null,
  email: null,
  mode_reglement: "virement",
  delai_reglement: 30,
  code_comptable: null,
  type_client: "C1",
  facturation_cp: false,
  code_ice: null,
  coef_heures_normales: 1.0,
  coef_heures_sup_25: 1.25,
  coef_heures_sup_50: 1.50,
  coef_heures_sup_100: 2.0,
  coef_heures_feriees: 2.0,
  coef_indemnites_soumises: 1.0,
  coef_indemnites_non_soumises: 1.0,
  coef_conge_paye: 1.0,
  coef_prime: 1.0,
  duree_hebdomadaire: 44,
  horaires_travail: null,
  activation_stc: false,
  tva: "normale",
  mode_edition_facture: "global",
  contact_nom: null,
  code_commercial: null,
  is_active: true,
};

export default function Clients() {
  const [clients, setClients] = useState<Client[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [typeFilter, setTypeFilter] = useState<string>("all");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [selectedClient, setSelectedClient] = useState<Client | null>(null);
  const [newClient, setNewClient] = useState<Omit<ClientInsert, "code">>(emptyClient);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetchClients();
  }, []);

  const fetchClients = async () => {
    try {
      const { data, error } = await supabase
        .from("clients")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      setClients(data || []);
    } catch (error: any) {
      toast.error("Erreur lors du chargement des clients: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  const filteredClients = clients.filter((client) => {
    const matchesSearch =
      client.raison_sociale.toLowerCase().includes(searchTerm.toLowerCase()) ||
      client.code.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (client.email?.toLowerCase() || "").includes(searchTerm.toLowerCase());
    const matchesStatus =
      statusFilter === "all" ||
      (statusFilter === "active" && client.is_active) ||
      (statusFilter === "inactive" && !client.is_active);
    const matchesType = typeFilter === "all" || client.type_client === typeFilter;
    return matchesSearch && matchesStatus && matchesType;
  });

  const handleAddClient = async () => {
    if (!newClient.raison_sociale.trim()) {
      toast.error("La raison sociale est obligatoire");
      return;
    }

    setSaving(true);
    try {
      const { error } = await supabase.from("clients").insert({
        ...newClient,
        code: "", // Will be auto-generated by trigger
      });

      if (error) throw error;

      toast.success("Client ajouté avec succès");
      setNewClient(emptyClient);
      setIsAddDialogOpen(false);
      fetchClients();
    } catch (error: any) {
      toast.error("Erreur lors de l'ajout: " + error.message);
    } finally {
      setSaving(false);
    }
  };

  const handleEditClient = async () => {
    if (!selectedClient) return;

    setSaving(true);
    try {
      const { error } = await supabase
        .from("clients")
        .update({
          raison_sociale: selectedClient.raison_sociale,
          titre: selectedClient.titre,
          adresse: selectedClient.adresse,
          adresse_facturation: selectedClient.adresse_facturation,
          telephone: selectedClient.telephone,
          email: selectedClient.email,
          mode_reglement: selectedClient.mode_reglement,
          delai_reglement: selectedClient.delai_reglement,
          code_comptable: selectedClient.code_comptable,
          type_client: selectedClient.type_client,
          facturation_cp: selectedClient.facturation_cp,
          code_ice: selectedClient.code_ice,
          coef_heures_normales: selectedClient.coef_heures_normales,
          coef_heures_sup_25: selectedClient.coef_heures_sup_25,
          coef_heures_sup_50: selectedClient.coef_heures_sup_50,
          coef_heures_sup_100: selectedClient.coef_heures_sup_100,
          coef_heures_feriees: selectedClient.coef_heures_feriees,
          coef_indemnites_soumises: selectedClient.coef_indemnites_soumises,
          coef_indemnites_non_soumises: selectedClient.coef_indemnites_non_soumises,
          coef_conge_paye: selectedClient.coef_conge_paye,
          coef_prime: selectedClient.coef_prime,
          duree_hebdomadaire: selectedClient.duree_hebdomadaire,
          horaires_travail: selectedClient.horaires_travail,
          activation_stc: selectedClient.activation_stc,
          tva: selectedClient.tva,
          mode_edition_facture: selectedClient.mode_edition_facture,
          contact_nom: selectedClient.contact_nom,
          code_commercial: selectedClient.code_commercial,
          is_active: selectedClient.is_active,
        })
        .eq("id", selectedClient.id);

      if (error) throw error;

      toast.success("Client modifié avec succès");
      setIsEditDialogOpen(false);
      fetchClients();
    } catch (error: any) {
      toast.error("Erreur lors de la modification: " + error.message);
    } finally {
      setSaving(false);
    }
  };

  const handleDeleteClient = async (id: string) => {
    if (!confirm("Êtes-vous sûr de vouloir supprimer ce client ?")) return;

    try {
      const { error } = await supabase.from("clients").delete().eq("id", id);

      if (error) throw error;

      toast.success("Client supprimé avec succès");
      fetchClients();
    } catch (error: any) {
      toast.error("Erreur lors de la suppression: " + error.message);
    }
  };

  const ClientForm = ({
    client,
    setClient,
    isEdit = false,
  }: {
    client: Omit<ClientInsert, "code"> | Client;
    setClient: (client: any) => void;
    isEdit?: boolean;
  }) => (
    <Tabs defaultValue="general" className="w-full">
      <TabsList className="grid w-full grid-cols-5">
        <TabsTrigger value="general">Général</TabsTrigger>
        <TabsTrigger value="facturation">Facturation</TabsTrigger>
        <TabsTrigger value="coefficients">Coefficients</TabsTrigger>
        <TabsTrigger value="travail">Travail</TabsTrigger>
        <TabsTrigger value="systeme">Système</TabsTrigger>
      </TabsList>

      <TabsContent value="general" className="space-y-4 mt-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Raison Sociale *</Label>
            <Input
              value={client.raison_sociale}
              onChange={(e) => setClient({ ...client, raison_sociale: e.target.value })}
              placeholder="Nom de la société"
            />
          </div>
          <div className="space-y-2">
            <Label>Titre</Label>
            <Select
              value={client.titre || ""}
              onValueChange={(value) => setClient({ ...client, titre: value || null })}
            >
              <SelectTrigger>
                <SelectValue placeholder="Sélectionner" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="SA">SA</SelectItem>
                <SelectItem value="SOC">SOC</SelectItem>
                <SelectItem value="SARL">SARL</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2 col-span-2">
            <Label>Adresse</Label>
            <Input
              value={client.adresse || ""}
              onChange={(e) => setClient({ ...client, adresse: e.target.value || null })}
              placeholder="Adresse complète"
            />
          </div>
          <div className="space-y-2 col-span-2">
            <Label>Adresse de facturation</Label>
            <Input
              value={client.adresse_facturation || ""}
              onChange={(e) => setClient({ ...client, adresse_facturation: e.target.value || null })}
              placeholder="Si différente de l'adresse principale"
            />
          </div>
          <div className="space-y-2">
            <Label>Téléphone</Label>
            <Input
              value={client.telephone || ""}
              onChange={(e) => setClient({ ...client, telephone: e.target.value || null })}
              placeholder="+212 5XX XXX XXX"
            />
          </div>
          <div className="space-y-2">
            <Label>E-mail</Label>
            <Input
              type="email"
              value={client.email || ""}
              onChange={(e) => setClient({ ...client, email: e.target.value || null })}
              placeholder="contact@societe.ma"
            />
          </div>
          <div className="space-y-2">
            <Label>Nom du contact</Label>
            <Input
              value={client.contact_nom || ""}
              onChange={(e) => setClient({ ...client, contact_nom: e.target.value || null })}
              placeholder="Responsable du site"
            />
          </div>
          <div className="space-y-2">
            <Label>Code commercial</Label>
            <Input
              value={client.code_commercial || ""}
              onChange={(e) => setClient({ ...client, code_commercial: e.target.value || null })}
              placeholder="COM-XXX"
            />
          </div>
        </div>
      </TabsContent>

      <TabsContent value="facturation" className="space-y-4 mt-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Mode de règlement</Label>
            <Select
              value={client.mode_reglement || "virement"}
              onValueChange={(value: "cheque" | "traite" | "virement") =>
                setClient({ ...client, mode_reglement: value })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="cheque">Chèque</SelectItem>
                <SelectItem value="traite">Traite</SelectItem>
                <SelectItem value="virement">Virement</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Délai de règlement (jours)</Label>
            <Select
              value={String(client.delai_reglement || 30)}
              onValueChange={(value) =>
                setClient({ ...client, delai_reglement: parseInt(value) })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="30">30 jours</SelectItem>
                <SelectItem value="60">60 jours</SelectItem>
                <SelectItem value="90">90 jours</SelectItem>
                <SelectItem value="120">120 jours</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Code comptable (R.Cpt)</Label>
            <Input
              value={client.code_comptable || ""}
              onChange={(e) => setClient({ ...client, code_comptable: e.target.value || null })}
              placeholder="411XXX"
            />
          </div>
          <div className="space-y-2">
            <Label>Type de client</Label>
            <Select
              value={client.type_client || "C1"}
              onValueChange={(value: "C1" | "C2" | "C9") =>
                setClient({ ...client, type_client: value })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="C1">C1</SelectItem>
                <SelectItem value="C2">C2</SelectItem>
                <SelectItem value="C9">C9</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Code ICE</Label>
            <Input
              value={client.code_ice || ""}
              onChange={(e) => setClient({ ...client, code_ice: e.target.value || null })}
              placeholder="00XXXXXXXXXX00XX"
            />
          </div>
          <div className="flex items-center space-x-2 pt-6">
            <Switch
              checked={client.facturation_cp || false}
              onCheckedChange={(checked) =>
                setClient({ ...client, facturation_cp: checked })
              }
            />
            <Label>Facturation Congés payés (CP)</Label>
          </div>
        </div>
      </TabsContent>

      <TabsContent value="coefficients" className="space-y-4 mt-4">
        <div className="grid grid-cols-3 gap-4">
          <div className="space-y-2">
            <Label>Heures normales</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_heures_normales || 1}
              onChange={(e) =>
                setClient({ ...client, coef_heures_normales: parseFloat(e.target.value) || 1 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>HS 25%</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_heures_sup_25 || 1.25}
              onChange={(e) =>
                setClient({ ...client, coef_heures_sup_25: parseFloat(e.target.value) || 1.25 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>HS 50%</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_heures_sup_50 || 1.5}
              onChange={(e) =>
                setClient({ ...client, coef_heures_sup_50: parseFloat(e.target.value) || 1.5 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>HS 100%</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_heures_sup_100 || 2}
              onChange={(e) =>
                setClient({ ...client, coef_heures_sup_100: parseFloat(e.target.value) || 2 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Heures fériées/chômées</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_heures_feriees || 2}
              onChange={(e) =>
                setClient({ ...client, coef_heures_feriees: parseFloat(e.target.value) || 2 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Indemnités soumises</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_indemnites_soumises || 1}
              onChange={(e) =>
                setClient({ ...client, coef_indemnites_soumises: parseFloat(e.target.value) || 1 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Indemnités non soumises</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_indemnites_non_soumises || 1}
              onChange={(e) =>
                setClient({
                  ...client,
                  coef_indemnites_non_soumises: parseFloat(e.target.value) || 1,
                })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Congé payé</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_conge_paye || 1}
              onChange={(e) =>
                setClient({ ...client, coef_conge_paye: parseFloat(e.target.value) || 1 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Coefficient Prime</Label>
            <Input
              type="number"
              step="0.01"
              value={client.coef_prime || 1}
              onChange={(e) =>
                setClient({ ...client, coef_prime: parseFloat(e.target.value) || 1 })
              }
            />
          </div>
        </div>
      </TabsContent>

      <TabsContent value="travail" className="space-y-4 mt-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Durée hebdomadaire (heures)</Label>
            <Input
              type="number"
              value={client.duree_hebdomadaire || 44}
              onChange={(e) =>
                setClient({ ...client, duree_hebdomadaire: parseInt(e.target.value) || 44 })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Horaires de travail</Label>
            <Input
              value={client.horaires_travail || ""}
              onChange={(e) => setClient({ ...client, horaires_travail: e.target.value || null })}
              placeholder="08:00 - 17:00"
            />
          </div>
        </div>
      </TabsContent>

      <TabsContent value="systeme" className="space-y-4 mt-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center space-x-2">
            <Switch
              checked={client.activation_stc || false}
              onCheckedChange={(checked) =>
                setClient({ ...client, activation_stc: checked })
              }
            />
            <Label>Activation STC</Label>
          </div>
          <div className="space-y-2">
            <Label>TVA</Label>
            <Select
              value={client.tva || "normale"}
              onValueChange={(value: "normale" | "exoneree" | "reduite") =>
                setClient({ ...client, tva: value })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="normale">Normale (20%)</SelectItem>
                <SelectItem value="exoneree">Exonérée</SelectItem>
                <SelectItem value="reduite">Réduite (7%)</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Mode d'édition facture</Label>
            <Select
              value={client.mode_edition_facture || "global"}
              onValueChange={(value: "global" | "salarie" | "commande") =>
                setClient({ ...client, mode_edition_facture: value })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="global">Global</SelectItem>
                <SelectItem value="salarie">Par salarié</SelectItem>
                <SelectItem value="commande">Par commande</SelectItem>
              </SelectContent>
            </Select>
          </div>
          {isEdit && (
            <div className="space-y-2">
              <Label>Statut</Label>
              <Select
                value={(client as Client).is_active ? "active" : "inactive"}
                onValueChange={(value) =>
                  setClient({ ...client, is_active: value === "active" })
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">Actif</SelectItem>
                  <SelectItem value="inactive">Inactif</SelectItem>
                </SelectContent>
              </Select>
            </div>
          )}
        </div>
      </TabsContent>
    </Tabs>
  );

  const formatPaymentMode = (mode: string | null) => {
    switch (mode) {
      case "cheque": return "Chèque";
      case "traite": return "Traite";
      case "virement": return "Virement";
      default: return mode || "-";
    }
  };

  const formatTva = (tva: string | null) => {
    switch (tva) {
      case "normale": return "Normale (20%)";
      case "exoneree": return "Exonérée";
      case "reduite": return "Réduite (7%)";
      default: return tva || "-";
    }
  };

  const formatInvoiceMode = (mode: string | null) => {
    switch (mode) {
      case "global": return "Global";
      case "salarie": return "Par salarié";
      case "commande": return "Par commande";
      default: return mode || "-";
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Clients</h1>
          <p className="text-muted-foreground">
            Gestion des clients et de leurs paramètres
          </p>
        </div>
        <Sheet open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
          <SheetTrigger asChild>
            <Button className="gap-2">
              <Plus className="w-4 h-4" />
              Nouveau client
            </Button>
          </SheetTrigger>
          <SheetContent side="right" className="w-full sm:max-w-2xl overflow-y-auto">
            <SheetHeader>
              <SheetTitle>Ajouter un nouveau client</SheetTitle>
              <SheetDescription>
                Remplissez les informations du nouveau client
              </SheetDescription>
            </SheetHeader>
            <div className="mt-6">
              <ClientForm client={newClient} setClient={setNewClient} />
              <div className="flex justify-end gap-2 mt-6">
                <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                  Annuler
                </Button>
                <Button onClick={handleAddClient} disabled={saving}>
                  {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  Ajouter
                </Button>
              </div>
            </div>
          </SheetContent>
        </Sheet>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total clients</CardTitle>
            <Building2 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{clients.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Clients actifs</CardTitle>
            <Building2 className="h-4 w-4 text-green-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              {clients.filter((c) => c.is_active).length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Clients inactifs</CardTitle>
            <Building2 className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-red-600">
              {clients.filter((c) => !c.is_active).length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Type C1</CardTitle>
            <Building2 className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {clients.filter((c) => c.type_client === "C1").length}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
              <Input
                placeholder="Rechercher par nom, code ou email..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Statut" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Tous les statuts</SelectItem>
                <SelectItem value="active">Actif</SelectItem>
                <SelectItem value="inactive">Inactif</SelectItem>
              </SelectContent>
            </Select>
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Tous les types</SelectItem>
                <SelectItem value="C1">C1</SelectItem>
                <SelectItem value="C2">C2</SelectItem>
                <SelectItem value="C9">C9</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Clients Table */}
      <Card>
        <CardContent className="pt-6">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Code</TableHead>
                <TableHead>Raison Sociale</TableHead>
                <TableHead>Contact</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Règlement</TableHead>
                <TableHead>Statut</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredClients.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                    Aucun client trouvé
                  </TableCell>
                </TableRow>
              ) : (
                filteredClients.map((client) => (
                  <TableRow key={client.id}>
                    <TableCell className="font-medium">{client.code}</TableCell>
                    <TableCell>
                      <div>
                        <p className="font-medium">{client.raison_sociale}</p>
                        <p className="text-sm text-muted-foreground">{client.titre || "-"}</p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="space-y-1">
                        <div className="flex items-center gap-1 text-sm">
                          <Mail className="w-3 h-3" />
                          {client.email || "-"}
                        </div>
                        <div className="flex items-center gap-1 text-sm text-muted-foreground">
                          <Phone className="w-3 h-3" />
                          {client.telephone || "-"}
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{client.type_client}</Badge>
                    </TableCell>
                    <TableCell>
                      <div className="text-sm">
                        <p>{formatPaymentMode(client.mode_reglement)}</p>
                        <p className="text-muted-foreground">{client.delai_reglement}j</p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge
                        variant={client.is_active ? "default" : "secondary"}
                        className={
                          client.is_active
                            ? "bg-green-100 text-green-800 hover:bg-green-100"
                            : "bg-red-100 text-red-800 hover:bg-red-100"
                        }
                      >
                        {client.is_active ? "Actif" : "Inactif"}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => {
                            setSelectedClient(client);
                            setIsViewDialogOpen(true);
                          }}
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => {
                            setSelectedClient(client);
                            setIsEditDialogOpen(true);
                          }}
                        >
                          <Edit className="w-4 h-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleDeleteClient(client.id)}
                        >
                          <Trash2 className="w-4 h-4 text-destructive" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* View Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              Détails du client - {selectedClient?.code}
            </DialogTitle>
            <DialogDescription>
              Informations complètes du client
            </DialogDescription>
          </DialogHeader>
          {selectedClient && (
            <div className="space-y-6">
              <Tabs defaultValue="general">
                <TabsList className="grid w-full grid-cols-5">
                  <TabsTrigger value="general">Général</TabsTrigger>
                  <TabsTrigger value="facturation">Facturation</TabsTrigger>
                  <TabsTrigger value="coefficients">Coefficients</TabsTrigger>
                  <TabsTrigger value="travail">Travail</TabsTrigger>
                  <TabsTrigger value="systeme">Système</TabsTrigger>
                </TabsList>

                <TabsContent value="general" className="mt-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label className="text-muted-foreground">Raison Sociale</Label>
                      <p className="font-medium">{selectedClient.raison_sociale}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Titre</Label>
                      <p className="font-medium">{selectedClient.titre || "-"}</p>
                    </div>
                    <div className="col-span-2">
                      <Label className="text-muted-foreground">Adresse</Label>
                      <p className="font-medium flex items-center gap-2">
                        <MapPin className="w-4 h-4" />
                        {selectedClient.adresse || "-"}
                      </p>
                    </div>
                    <div className="col-span-2">
                      <Label className="text-muted-foreground">Adresse de facturation</Label>
                      <p className="font-medium">{selectedClient.adresse_facturation || "-"}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Téléphone</Label>
                      <p className="font-medium flex items-center gap-2">
                        <Phone className="w-4 h-4" />
                        {selectedClient.telephone || "-"}
                      </p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">E-mail</Label>
                      <p className="font-medium flex items-center gap-2">
                        <Mail className="w-4 h-4" />
                        {selectedClient.email || "-"}
                      </p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Nom du contact</Label>
                      <p className="font-medium">{selectedClient.contact_nom || "-"}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Code commercial</Label>
                      <p className="font-medium">{selectedClient.code_commercial || "-"}</p>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="facturation" className="mt-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label className="text-muted-foreground">Mode de règlement</Label>
                      <p className="font-medium">{formatPaymentMode(selectedClient.mode_reglement)}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Délai de règlement</Label>
                      <p className="font-medium">{selectedClient.delai_reglement} jours</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Code comptable</Label>
                      <p className="font-medium">{selectedClient.code_comptable || "-"}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Type de client</Label>
                      <Badge variant="outline">{selectedClient.type_client}</Badge>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Code ICE</Label>
                      <p className="font-medium">{selectedClient.code_ice || "-"}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Facturation CP</Label>
                      <Badge variant={selectedClient.facturation_cp ? "default" : "secondary"}>
                        {selectedClient.facturation_cp ? "Oui" : "Non"}
                      </Badge>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="coefficients" className="mt-4 space-y-4">
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <Label className="text-muted-foreground">Heures normales</Label>
                      <p className="font-medium">{selectedClient.coef_heures_normales}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">HS 25%</Label>
                      <p className="font-medium">{selectedClient.coef_heures_sup_25}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">HS 50%</Label>
                      <p className="font-medium">{selectedClient.coef_heures_sup_50}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">HS 100%</Label>
                      <p className="font-medium">{selectedClient.coef_heures_sup_100}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Heures fériées</Label>
                      <p className="font-medium">{selectedClient.coef_heures_feriees}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Indemnités soumises</Label>
                      <p className="font-medium">{selectedClient.coef_indemnites_soumises}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Indemnités non soumises</Label>
                      <p className="font-medium">{selectedClient.coef_indemnites_non_soumises}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Congé payé</Label>
                      <p className="font-medium">{selectedClient.coef_conge_paye}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Prime</Label>
                      <p className="font-medium">{selectedClient.coef_prime}</p>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="travail" className="mt-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label className="text-muted-foreground">Durée hebdomadaire</Label>
                      <p className="font-medium">{selectedClient.duree_hebdomadaire} heures</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Horaires de travail</Label>
                      <p className="font-medium">{selectedClient.horaires_travail || "-"}</p>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="systeme" className="mt-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label className="text-muted-foreground">Activation STC</Label>
                      <Badge variant={selectedClient.activation_stc ? "default" : "secondary"}>
                        {selectedClient.activation_stc ? "Oui" : "Non"}
                      </Badge>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">TVA</Label>
                      <p className="font-medium">{formatTva(selectedClient.tva)}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Mode d'édition facture</Label>
                      <p className="font-medium">{formatInvoiceMode(selectedClient.mode_edition_facture)}</p>
                    </div>
                    <div>
                      <Label className="text-muted-foreground">Statut</Label>
                      <Badge
                        variant={selectedClient.is_active ? "default" : "secondary"}
                        className={
                          selectedClient.is_active
                            ? "bg-green-100 text-green-800"
                            : "bg-red-100 text-red-800"
                        }
                      >
                        {selectedClient.is_active ? "Actif" : "Inactif"}
                      </Badge>
                    </div>
                  </div>
                </TabsContent>
              </Tabs>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Edit Sheet */}
      <Sheet open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <SheetContent side="right" className="w-full sm:max-w-2xl overflow-y-auto">
          <SheetHeader>
            <SheetTitle>
              Modifier le client - {selectedClient?.code}
            </SheetTitle>
            <SheetDescription>
              Modifiez les informations du client
            </SheetDescription>
          </SheetHeader>
          {selectedClient && (
            <div className="mt-6">
              <ClientForm
                client={selectedClient}
                setClient={setSelectedClient}
                isEdit
              />
              <div className="flex justify-end gap-2 mt-6">
                <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
                  Annuler
                </Button>
                <Button onClick={handleEditClient} disabled={saving}>
                  {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  Enregistrer
                </Button>
              </div>
            </div>
          )}
        </SheetContent>
      </Sheet>
    </div>
  );
}
